// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BlogPostList: typeof import('./src/components/BlogPostList.vue')['default']
    CmTickets3Sept: typeof import('./src/components/CmTickets3Sept.vue')['default']
    ContactForm: typeof import('./src/components/ContactForm.vue')['default']
    EasyLightbox: typeof import('./src/components/EasyLightbox.vue')['default']
    FooterComponent: typeof import('./src/components/FooterComponent.vue')['default']
    IkBenAanwezig20Augustus: typeof import('./src/components/IkBenAanwezig20Augustus.vue')['default']
    ImageGallery: typeof import('./src/components/ImageGallery.vue')['default']
    LanguageSwitcher: typeof import('./src/components/LanguageSwitcher.vue')['default']
    LatestBlogPost: typeof import('./src/components/LatestBlogPost.vue')['default']
    MarkdownWrapper: typeof import('./src/components/MarkdownWrapper.vue')['default']
    NavbarComponent: typeof import('./src/components/NavbarComponent.vue')['default']
    NextPreviousPost: typeof import('./src/components/NextPreviousPost.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SocialIcons: typeof import('./src/components/SocialIcons.vue')['default']
  }
}
