// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BlogPostList: typeof import('./src/components/BlogPostList.vue')['default']
    FooterComponent: typeof import('./src/components/FooterComponent.vue')['default']
    LanguageSwitcher: typeof import('./src/components/LanguageSwitcher.vue')['default']
    MarkdownWrapper: typeof import('./src/components/MarkdownWrapper.vue')['default']
    NavbarComponent: typeof import('./src/components/NavbarComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TranslatedSection: typeof import('./src/components/TranslatedSection.vue')['default']
  }
}
