// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    FooterComponent: typeof import("./src/components/FooterComponent.vue")["default"];
    MarkdownWrapper: typeof import("./src/components/MarkdownWrapper.vue")["default"];
    NavbarComponent: typeof import("./src/components/NavbarComponent.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
  }
}
