[build]
  command = "pnpm run build || ( npm install pnpm && pnpm run build )"
  publish = "dist"
  environment = { NODE_VERSION = "16" }

[build.environment]
    NPM_FLAGS = "--prefix=/dev/null"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Opting your Website out of Google's FLoC Network
[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"