version: 2.1

orbs:
  node: circleci/node@5.0.2
  sonarcloud: sonarsource/sonarcloud@1.1.0

executors:
  node-executor:
    docker:
      - image: cimg/node:16.15
        auth:
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD

jobs:
  setup:
    executor:
      name: node/default
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install pnpm
          command: curl -L https://pnpm.js.org/pnpm.js | node - add --global pnpm
      - run:
          name: Install packages
          command: pnpm install --no-frozen-lockfile
      - save_cache:
          key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - ~/.nvm
            - node_modules
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Build
          command: |
            pnpm run build
            ls dist
      - save_cache:
          key: build-output-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - dist
      - store_artifacts:
          path: dist
          destination: dist
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Test and Lint
          command: pnpm run lint && pnpm test
      - sonarcloud/scan

workflows:
  version: 2
  build_and_test:
    jobs:
      - setup
      - build:
          requires:
            - setup
      - test:
          requires:
            - setup
          context: SonarCloud
