version: 2.1

orbs:
  node: circleci/node@5.0.2
  sonarcloud: sonarsource/sonarcloud@1.1.1

jobs:
  build_and_test:
    docker:
      - image: vernaillen/circleci-pnpm:18.2.0
    steps:
      - checkout
      - run:
          name: Install packages
          command: pnpm install --no-frozen-lockfile
      - run:
          name: Lint
          command: pnpm run lint
      - run:
          name: Test
          command: pnpm test
      - sonarcloud/scan
      - run:
          name: Build
          command: |
            pnpm run build
            ls dist

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build_and_test:
          context: SonarCloud