version: 2.1

orbs:
  slack: circleci/slack@4.12.1

executors:
  pnpm-executor:
    docker:
      - image: vernaillen/circleci-pnpm:19.5.0-browsers
    working_directory: /tmp/workspace

jobs:
  build:
    executor: pnpm-executor
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install packages
          command: pnpm install --no-frozen-lockfile
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build
          command: pnpm run generate
      - persist_to_workspace:
          root: .
          paths:
            - package.json
            - pnpm-lock.yaml
            - node_modules
            - cypress
            - cypress.config.ts
            - nuxt.config.ts
            - .nuxt
            - tsconfig.json
            - src
            - test
            - dist
            - .gitignore
      - slack/notify:
          channel: circleci
          event: fail
  test:
    executor: pnpm-executor
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Test
          command: pnpm run coverage
      - slack/notify:
          channel: circleci
          event: fail
  e2e:
    executor: pnpm-executor
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Install Cypress
          command: pnpm run cy:install
      - run:
          name: Run Cypress
          command: pnpm run cy:run 
      - slack/notify:
          channel: circleci
          event: always

workflows:
  flow:
    jobs:
      - build:
          context: 
            - Slack
      - test:
          requires:
            - build
          context: 
            - Slack
      - e2e:
          requires:
            - test
          filters:
            branches:
              only: master
          context: 
            - Slack

# VS Code Extension Version: 1.5.1
