version: 2.1

orbs:
  slack: circleci/slack@4.12.5
  sonarcloud: sonarsource/sonarcloud@2.0.0

executors:
  pnpm-executor:
    docker:
      - image: cimg/node:20.5.1-browsers
    working_directory: /tmp/workspace

jobs:
  build:
    executor: pnpm-executor
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Check node version
          command: node -v
      - run:
          name: Check pnpm version
          command: pnpm -v
      - run:
          name: Install packages
          command: pnpm install --no-frozen-lockfile
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build
          command: pnpm run build
      - sonarcloud/scan
      - persist_to_workspace:
          root: .
          paths:
            - package.json
            - pnpm-lock.yaml
            - node_modules
            - cypress
            - cypress.config.ts
            - nuxt.config.ts
            - .nuxt
            - tsconfig.json
            - src
            - test
            - dist
            - .gitignore
      - slack/notify:
          channel: circleci
          event: fail
    # The resource_class feature allows configuring CPU and RAM resources for each job. Different resource classes are available for different executors. https://circleci.com/docs/2.0/configuration-reference/#resourceclass
    resource_class: large
  test:
    executor: pnpm-executor
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Test
          command: pnpm run coverage
      - slack/notify:
          channel: circleci
          event: fail
  e2e:
    executor: pnpm-executor
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Install Cypress
          command: pnpm run cy:install
      - run:
          name: Run Cypress
          command: pnpm run cy:run
      - slack/notify:
          channel: circleci
          event: always

workflows:
  flow:
    jobs:
      - build:
          context:
            - Slack
            - SonarCloud
      - test:
          requires:
            - build
          context:
            - Slack
      - e2e:
          requires:
            - test
          filters:
            branches:
              only: master
          context:
            - Slack

# VS Code Extension Version: 1.5.1
