version: 2.1

orbs:
  node: circleci/node@5.0.3
  sonarcloud: sonarsource/sonarcloud@1.1.1
  slack: circleci/slack@4.10.1

executors:
  pnpm-executor:
    docker:
      - image: vernaillen/circleci-pnpm:18.9.1-browsers
    working_directory: /tmp

jobs:
  build_test_deploy:
    executor: pnpm-executor
    steps:
      - checkout
      - run:
          name: Install packages
          command: pnpm install --no-frozen-lockfile
      - run:
          name: Lint
          command: pnpm run lint
      - run:
          name: Test
          command: pnpm test
      - sonarcloud/scan
      - run:
          name: Build
          command: |
            pnpm run netlify:build
      - run:
          name: Deploy
          command: |
            pnpm run netlify:deploy
      - persist_to_workspace:
          root: .
          paths:
            - package.json
            - node-modules
            - cypress
            - cypress.config.ts
      - slack/notify:
          channel: circleci
          event: always
  integration_test:
    executor: pnpm-executor
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: Run Cypress
          command: pnpm run cypress:run 
      - slack/notify:
          channel: circleci
          event: always

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build_test_deploy:
          context: 
            - SonarCloud
            - Slack
      - integration_test:
          requires:
            - build_test_deploy
          filters:
            branches:
              only: master
          context: 
            - Slack