version: 2.1

orbs:
  node: circleci/node@5.0.2
  sonarcloud: sonarsource/sonarcloud@1.0.3

executors:
  node-executor:
    docker:
      - image: cimg/node:16.14
        auth:
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: build
          command: npm run build
      - sonarcloud/scan

workflows:
  validate:
    jobs:
      - build:
          context: SonarCloud
