export const iubenda = {
  config: {
    siteId: 3000177,
    cookiePolicyId: 41044780,

    gdprAppliesGlobally: false,
    lang: 'nl',
    perPurposeConsent: true,
    whitelabel: false,
    cookiePolicyUrl: 'https://harmonics.be/cookiebeleid',
    banner: {
      acceptButtonColor: '#BFAC22',
      acceptButtonDisplay: true,
      backgroundOverlay: true,
      backgroundColor: '#FFFFFF',
      closeButtonDisplay: true,
      cookiePolicyInOtherWindow: true,
      customizeButtonColor: '#BFAC22',
      customizeButtonDisplay: true,
      customizeButtonCaptionColor: '#FFFFFF',
      explicitWithdrawal: false,
      listPurposes: false,
      linksColor: '#6B7280',
      position: 'float-bottom-center',
      rejectButtonColor: '#9CA3AF',
      rejectButtonDisplay: true,
      rejectButtonCaptionColor: '#FFFFFF',
      textColor: '#9CA3AF',
    },
  },
}
