export const iubenda = {
  config: {
    siteId: 3000177,
    cookiePolicyId: 41044780,

    gdprAppliesGlobally: false,
    cookiePolicyInOtherWindow: true,
    lang: 'nl',
    perPurposeConsent: true,
    whitelabel: false,
    cookiePolicyUrl: 'https://harmonics.be/cookiebeleid',
    banner: {
      fontSizeBody: '12px',
      acceptButtonColor: '#BFAC22',
      acceptButtonDisplay: true,
      acceptButtonCaption: 'Accepteren en doorgaan',
      backgroundOverlay: true,
      backgroundColor: '#FFFFFF',
      closeButtonDisplay: false,
      customizeButtonColor: '#9CA3AF',
      customizeButtonDisplay: true,
      customizeButtonCaption: 'Zelf instellen',
      customizeButtonCaptionColor: '#FFFFFF',
      explicitWithdrawal: false,
      listPurposes: false,
      linksColor: '#6B7280',
      position: 'float-bottom-center',
      rejectButtonColor: '#9CA3AF99',
      rejectButtonDisplay: true,
      rejectButtonCaption: 'Afwijzen',
      rejectButtonCaptionColor: '#FFFFFF',
      textColor: '#9CA3AF',
      content: '<h1>Fijn dat je er bent!</h1>Door op \\"Accepteren Doorgaan\\" te klikken ga je akkoord met het gebruik van alle cookies zoals beschreven in ons <a href=https:\/\/harmonics.be\/cookiebeleid target=_blank>cookie beleid<\/a>.',
    },
  },
}
